all:

	g++ -c CircularList.cpp
	g++ -c main.cpp
	g++ *.o -o vai
run:
	./vai

clean:
	del C:\Users\AirtonDoug\Desktop\c++\CircularListMoodle\*.o
	del C:\Users\AirtonDoug\Desktop\c++\CircularListMoodle\vai.exe